# Generated by Django 5.2.3 on 2025-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=20)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.CharField(max_length=20)),
                ('sender_station', models.CharField(max_length=20)),
                ('reciever_name', models.CharField(max_length=20)),
                ('reciever_phone', models.CharField(max_length=20)),
                ('reciever_address', models.CharField(max_length=20)),
                ('reciever_station', models.CharField(max_length=20)),
                ('awbno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('station', models.CharField(max_length=30)),
                ('activitylist', models.CharField(max_length=30)),
            ],
        ),
    ]
