# Generated by Django 5.2.3 on 2025-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdetails',
            name='awbno',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
