# Generated by Django 5.2.3 on 2025-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='pcs',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='wt',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transitdetails',
            name='date',
            field=models.DateField(),
        ),
    ]
