# Generated by Django 5.2.3 on 2025-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookingdata_pcs_bookingdata_wt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='reciever_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='sender_address',
            field=models.TextField(),
        ),
    ]
