# Generated by Django 5.2.3 on 2025-06-12 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookingdata_reciever_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 7, 7, 15, 55201, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
